// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/util/jwt/jwt.go

// Package jwt is a generated GoMock package.
package jwt

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockJwtInterface is a mock of JwtInterface interface.
type MockJwtInterface struct {
	ctrl     *gomock.Controller
	recorder *MockJwtInterfaceMockRecorder
}

// MockJwtInterfaceMockRecorder is the mock recorder for MockJwtInterface.
type MockJwtInterfaceMockRecorder struct {
	mock *MockJwtInterface
}

// NewMockJwtInterface creates a new mock instance.
func NewMockJwtInterface(ctrl *gomock.Controller) *MockJwtInterface {
	mock := &MockJwtInterface{ctrl: ctrl}
	mock.recorder = &MockJwtInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJwtInterface) EXPECT() *MockJwtInterfaceMockRecorder {
	return m.recorder
}

// ExtractToken mocks base method.
func (m *MockJwtInterface) ExtractToken(ctx context.Context, token string) (JwtData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExtractToken", ctx, token)
	ret0, _ := ret[0].(JwtData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExtractToken indicates an expected call of ExtractToken.
func (mr *MockJwtInterfaceMockRecorder) ExtractToken(ctx, token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExtractToken", reflect.TypeOf((*MockJwtInterface)(nil).ExtractToken), ctx, token)
}

// GenerateToken mocks base method.
func (m *MockJwtInterface) GenerateToken(ctx context.Context, data JwtData) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateToken", ctx, data)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateToken indicates an expected call of GenerateToken.
func (mr *MockJwtInterfaceMockRecorder) GenerateToken(ctx, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateToken", reflect.TypeOf((*MockJwtInterface)(nil).GenerateToken), ctx, data)
}
